import Head from 'next/head'
import BasicProductTile from "../../components/BasicProductTile";

export default function OpenEditionPrints(props) {

    let baseSlug = 'open-edition-prints';
    return (
        <>
            <Head>
                <title>SHOP / Lostpixels</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className='flex col-start-2 col-span-10 md:col-start-3 md:col-span-8 mb-8'>
                {props.products.map(p => <BasicProductTile className='basis-1/3' baseSlug={baseSlug} key={p.id} {...p} />)}
            </div>
        </>
    )
}

export async function getStaticProps() {

    let data = await fetch('https://clownfish-app-f4hhn.ondigitalocean.app/api/open-edition-prints?populate=*');
    data = await data.json();

    return {
        props: {
            products: data.data
        }
    }
}

